name: Step 1 # Create a branch

# Checks if the learner completed tasks for step 1.
# - Triggers when the user creates a new branch 'my-first-branch'.
# - Checks that the branch name is 'my-first-branch'.
# - If all checks pass, the workflow is disabled so it doesn't run again. As such, workflow status badge will change to green.

on:
  push:
    branches:
      - "!main"
      - "my-first-branch"

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  find_lesson:
    name: Find lesson by issue title
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template

    outputs:
      issue-url: ${{ steps.get-issue-url-by-title.outputs.ISSUE_URL }}

    steps:
      - id: get-issue-url-by-title
        run: |
          issue_url=$(gh issue list --repo ${{ github.repository }} --search "in:title Course:" --json url,title --jq '.[].url')
          echo "ISSUE_URL=$issue_url" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: find_lesson
    if: |
      !github.event.repository.is_template
    env:
      ISSUE_URL: ${{ needs.find_lesson.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Update comment - checking work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file skills-response-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build message - step finished
        id: build-message-step-finish
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number=2

      - name: Update comment - step finished
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "${{ steps.build-message-step-finish.outputs.updated-text }}" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_next_step_content:
    name: Post next step content
    needs: [find_lesson, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_lesson.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/skills-response-templates
          path: skills-response-templates

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file .github/steps/2-commit-a-file.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file skills-response-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "Step 1"
          gh workflow enable "Step 2"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
