name: Step 4 # Merge your pull request

# Checks if the learner completed tasks for step 4.
# - Triggers when the user merges the pull request.
# - If all checks pass, the workflow is disabled so it doesn't run again. As such, workflow status badge will change to green.

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  actions: write
  issues: write

env:
  REVIEW_FILE: ".github/steps/x-review.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.1.0

  check_step_work:
    name: Check step work
    needs: find_exercise
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template &&
      github.head_ref == 'my-first-branch' &&
      github.event.pull_request.merged == true
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.0

      - name: Nothing to check
        run: echo "The workflow was triggered, so it passes."

      - name: Update comment - step finished - final review next
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/lesson-review.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_review_content:
    name: Post review content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create comment - add review content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ${{ env.REVIEW_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.4.0
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}


  disable_workflow:
    name: Disable this workflow
    needs: [find_exercise, post_review_content]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Disable current workflow
        run: gh workflow disable "${{github.workflow}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

